### ISSUE TITLE
Load data file(s) site-wide, vs page-by-page basis

### ISSUE THREAD

**Issue by doublejosh** [tests-always-included/metalsmith-data-loader#11]
Would be lovely to specify files to load as site-wide globally available data for use in common partials or just info needed on most pages... without having to specify the loaded file and/or passing the data into a partial as a variable.

**Comment by fidian** [comment]
I don't think that loading data globally is the focus of this plugin. It looks at metadata in files and loads the specified files. What I think you need is something along the lines of the following:

    Metalsmith(__dirname)
        .source("src/")
        .destination("dest/")
        .metadata({
            file1: require("./file1.json"),
            file2: require("./file2.json")
        })
        .use(markdown())
        .build((err) => {
            if (err) throw err;
        });

If something like this doesn't work for you, I suggest you please inform me and demonstrate how you would want to use this plugin to load data globally. A code example should be sufficient. I'd like to see something similar to what's above, if you would be so kind.

**Comment by doublejosh** [comment]
Thanks for the reply! Quite right, that could perhaps be done very simply outside plugins.

I discovered some other plugin options focused on this goal...
- https://github.com/elcontraption/metalsmith-data (recommended)
- https://github.com/iskolbin/metalsmith-globaldata
