### ISSUE TITLE
Unable to ignore missing extras files

### ISSUE THREAD

**Issue by SDaron** [tests-always-included/metalsmith-data-loader#12]
I'm trying to use this plugin in combination with collection metadata in order to automatically load extras if the files is present in the directory.
```
        "metalsmith-collection-metadata":{
	        "collections.X": {"extras": "contacts.yaml"}
        },
        "metalsmith-data-loader": {
            "dataProperty": "extras",
            "match": "**/*.md",
            "matchOptions": {},
            "removeSource": true
        }
```
But some directories don't have a file "contact.yaml", causing the whole builing process to fail. Is their a way to to that, or what would you think about adding a "ignoreMissingFile" option to allow this kind of use as a global logic instead of a per page basis?

**Comment by fidian** [comment]
I don't normally want to ignore that a file is missing, though I could see it as a very useful option, especially in your case. Would you think that this syntax would work? It doesn't exist now; I am just proposing a possible way we could solve the problem.

    "metalsmith-data-loader": {
        "dataProperty": "extras",
        "ignoreReadFailure": true,
        "match": "**/*.md",
        "matchOptions": {},
        "removeSource": true
    }

I take it that you didn't want to make this PR yourself? That's not an issue. I think I have some time this week to make this suggestion come to life if we implement it as a simple, configurable option.

**Comment by SDaron** [comment]
Thanks for your answer. This syntax would work and will solve my problem. I've writed a PR.
