### ISSUE TITLE
`removeSource` not working as expected

### ISSUE THREAD

**Issue by hsucherng** [tests-always-included/metalsmith-data-loader#14]
Hey there,

I would like to report an issue that I'm currently facing, where setting `removeSource` to `true` does not lead to the data files being removed from the output.

I tested this with a bare-bones project: 

```
node_modules
src
    `-- index.html
    `-- index.yaml
build.js
package.json
yarn.lock
```

`index.html`:

```html
---
data: index.yaml
---

<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <p>Test project</p>
    </body>
</html>
```

`index.yaml`:

```yaml
title: "Testing YAML"
```

`build.js`:

```js
const Metalsmith = require('metalsmith');
const dataLoader = require('metalsmith-data-loader');

Metalsmith(__dirname)
    .source('src')
    .destination('build')
    .use(dataLoader({
        removeSource: true
    }))
    .build(function(err, files) {
        console.log(files['index.html'].data);
        console.log(`Build complete!`);
    });
```

After running `node build`, I can see that the data from `index.yaml` had been correctly added into the `index.html` file, but the data file is still present in the build folder. I'm expecting only the `index.html` file in `build` folder.

I poked around the code a little, and I currently suspect that it has something to do with the resolved path inside the `removeSource` function. When I changed it from `path.resolve` to `path.join`, the plugin is then able to remove the data file as expected. Not sure if that would make for an appropriate solution though.

**Comment by fidian** [comment]
I tried to replicate what you are seeing but am unable. Your files have been added to a test repository at https://github.com/fidian/metalsmith-data-loader-issue-14 - would you be willing to clone and see if the destination folder contains `index.yaml` after being built?

It is possible that the `index.yaml` type files you are seeing are leftover from a previous build.

**Comment by hsucherng** [comment]
@fidian Strange, as I am able to replicate it with that test repository. I cloned it, ran `npm ci`, then ran `node build`, and I see that the destination folder contains the `index.yaml` file.

**Comment by fidian** [comment]
This is a screenshot of me trying the same thing. What could be the differences between our setups?

![Screenshot from 2019-11-29 18-40-10](https://user-images.githubusercontent.com/428348/69893508-d213c100-12d7-11ea-9026-d6e5b1924366.png)

The installation is using metalsmith 2.3.0 and metalsmith-data-loader 1.1.3. If we have roughly the same setup, the next step is maybe adding some debugging within `lib/index.js`. So if it is still happening on your side, would you be willing to add this chunk of code within the `removeSource()` function?

    console.log({
        options: options,
        modelFile: modelFile,
        pathSep: path.sep,
        sourceFile: sourceFile
    });

**Comment by fidian** [comment]
I was thinking about this a bit more and would like to know what environment you are using - Windows, Linux, Mac, or other? Is it reproducable on other machines that you can easily access?

**Comment by hsucherng** [comment]
I've added the chunk of code within the `removeSource()` function, this is what I get:

![image](https://user-images.githubusercontent.com/7273177/70029072-2e7d2600-15e1-11ea-9114-f5692ca15e48.png)

I'm on a Windows environment.

I've got access to a Mac, and can confirm that it does *not* occur on it.

**Comment by fidian** [comment]
I've found some strange behavior with different platforms. When I run the commands via the REPL I get one result and tests get another result. Then there's the posix / win32 differences. It looks like using `path.join()` would not be adequate.

POSIX:

```
path.resolve(path.sep, 'index.html', '..', 'data.yaml')
-> /data.yaml (cli)
-> data.yaml (tests)

path.join(path.sep, 'a/index.html', '..', '/data.yaml')
-> /a/data.yaml (cli)
-> a/data.yaml (tests)
```

WIN32:
```
path.resolve(path.sep, 'index.html', '..', 'data.yaml')
-> C:\\data.yaml (cli)
-> :\\data.yaml (tests)

path.join(path.sep, 'a\\index.html', '..', '/data.yaml')
-> \\data.yaml (cli)
-> a\\data.yaml (test)
```

With these results, it appears that using `path.join()` won't work for me because I need the `/data.yaml` to be an absolute path. I would like to know why I am getting different results in tests versus the REPL. After that, I suspect my solution will use `path.resolve()` and remove a prefix if one is found, possibly using different patterns based on `path.sep` or `path === path.win32`.

Thanks for working with me to find the solution!

**Comment by fidian** [comment]
Ok, I'm not terribly observant today. The tests were slicing off the first character, so for win32 `C:\` turns into `:\`. I have added code and a couple tests for this situation and everything seems to be passing fine on Windows for me. Version 1.1.4 was released. The repository I created earlier from your code is working for me.

Does this solve the problem on your side as well?

**Comment by hsucherng** [comment]
Yes, it does solve the problem on my side. :)

Thank you very much for your time! I will go ahead and close this issue.

**Comment by fidian** [comment]
Excellent. I'm glad that it worked. Thank you for reporting the issue and taking the preliminary steps to investigate. Sorry that I couldn't address this bug sooner, and I am glad that this all worked out in the end.
