### ISSUE TITLE
Setting directory has no effect (unclear docs)

### ISSUE THREAD

**Issue by willdady** [tests-always-included/metalsmith-data-loader#2]
The readme implies doing the following should work.

```
.source('./src')
.destination('./dist')
.use(
  dataLoader({
    directory: 'models/'
  })
)
```

My src file

```
---
title: Some file
data: mydata.yml
---
```

I would expect the file at `src/models/mydata.yml` to be loaded however it tries to load `src/mydata.yml`.

Looking at the source it seems I need to prefix the data path with `!` so that it loads from the models directory however this isn't documented in the ReadMe :\

**Comment by fidian** [comment]
I have updated the `README.md` and included examples of how it works.  Would you review it and make sure it is clear?

https://github.com/tests-always-included/metalsmith-data-loader#user-content-resolving-files

**Comment by fidian** [comment]
Closing due to a lack of feedback.

I've also made an example repository to help show how file resolution can work.
