### ISSUE TITLE
never resolved data path

### ISSUE THREAD

**Issue by gishnanigans** [tests-always-included/metalsmith-data-loader#7]
I tried to include a `*.yaml` file outside of the `src` directory and set the `directory: *` to every conceivable value using both the default `models` and my own custom directory name `data`
```
'models' (expected to work)
'models/'
'/models/'
'./models'
'./models/'
```
And I tried not setting the directory at all...

I also included the `data: !items.yaml` inside the front matter of the file to point to the directory outside of `src`

Not only did it not load any data, it also "ate" the other front-matter on that page e.g. `layout: my-layout.html`

So... no dice. I'm not willing to struggle this hard for this unless you know what is going on.

In the meantime I'm going back to using `metalsmith-metadata` which just works. However, I would still prefer to keep my data outside of my `src` directory.

Thoughts?

**Comment by fidian** [comment]
I think I should make a sample project so others can see how this plugin works and to prove that it works as advertised.

The really interesting bit is when you say it ate other front-matter on the page. This plugin doesn't delete metadata, its worst outcome is metadata properties are overwritten. Do you have a way for me to look at a repository and see this behavior in action?

**Comment by fidian** [comment]
I've made an example repository to show how the plugin works. I can't seem to replicate the issues you experienced. Want to see if you can alter the example to get it to overwrite existing properties?

https://github.com/fidian/metalsmith-data-loader-example

**Comment by gishnanigans** [comment]
I'm sorry. I haven't tried it again yet but I figured out what was happening to my other front-matter and almost definitely why data-loader wasn't working also. I had a single line above my front-matter block on my test page. Upon further investigation I realized metalsmtih wasn't getting any of my front-matter and it was still in the contents buffer of that file.

```
// empty line
---
data: !items.yaml
---
// some more content...

```
I'll try again with data-loader when I get a chance. You can probably safely close this issue.

**Comment by fidian** [comment]
I completely understand; I've done very similar things. Let me know if you have further issues with this plugin and I will help.
