### ISSUE TITLE
This plugin does not support JSON

### ISSUE THREAD

**Issue by kellyChap** [tests-always-included/metalsmith-data-loader#8]
I have spent most of the day trying to get this plugin to work with JSON and it definitely does not work witj JSON.  It only seems to work when I transported everything to YAML.

Please update the doco or fix the issue.

**Comment by fidian** [comment]
The example works with JSON just fine. Look at the file in `models/`, then run the build and look at `dest/model.md`.

    https://github.com/fidian/metalsmith-data-loader-example

Can you provide an example of where it is not working?

**Comment by fidian** [comment]
@kellyChap Did you have time to look at the examples? Is it still not working in your project?

**Comment by fidian** [comment]
It may be wrong of me, but I am going to assume that there was another issue that prevented JSON from showing up in the way you expected. If that assumption is wrong, please comment here and I'll reopen this issue or you can make a new one and provide an example illustrating how it is failing for you.
